### ISSUE TITLE
Mehrere Positionen einfügen

### ISSUE THREAD

**Issue by rittersportler11** [Digitalschmiede/fastbill#4]
Hallo,
als erstes möchte ich mich bei Ihnen für das bereitstellen vielmals bedanken. Das ist genau das was ich gesucht habe.

Leider gelingt es mir im Moment noch nicht 2 oder mehr Positionen in ein Angebot einzufügen.
Das einfügen einer einzelnen Position mit Preis und Beschreibung zur internen Kundennummer stellt kein Problem dar und wird wie folgt realisiert:

$fastbill->request(array("SERVICE" => "estimate.create", "DATA" => array("CUSTOMER_ID" => "00000","ITEMS"=>array("DESCRIPTION"=>"test", "UNIT_PRICE"=>"5" ))));

Haben Sie einen Tipp für mich wie man das Problem lösen könnte?! Oder ist dies nicht vorgesehen?

Nochmals vielen Dank!

**Comment by Digitalschmiede** [comment]
Guten Abend,

In die Items muss ein Array mit (pro Item) jeweils einem eigenem Array:
> $fastbill->request(array("SERVICE" => "estimate.create", "DATA" => array("CUSTOMER_ID" => "00000","ITEMS"=>array(array("DESCRIPTION"=>"test", "UNIT_PRICE"=>"5" ), array(), array(), ...))));
> 

Mit freundlichen Grüßen,

Andreas Schneider
