### ISSUE TITLE
Initialisieren von Fastbill

### ISSUE THREAD

**Issue by bert2002** [Digitalschmiede/fastbill#5]
Hi,

bin gerade dabei einen kleinen Test mit FastBill zu machen und bin dabei auf Eure lib gestoßen. Sieht gut aus, aber irgendwie will er nicht so wie ich. Z.B.:

```
require('config.php');
require('../../fastbill/fastbill.1.2.php');
$fastbill = new fastbill(string $FASTBILL_EMAIL, string $FASTBILL_KEY [, string $apiUrl = FASTBILL_PLUS]);
```

Als Ergebnis in der Apache Error Log:
```
PHP Parse error:  syntax error, unexpected '$FASTBILL_EMAIL' (T_VARIABLE) in ...
```
Die Variablen werden in der config.php gesetzt und sind auch vorhanden. Irgendwie verstehe ich nicht was das Problem sein soll.

Danke

**Comment by Digitalschmiede** [comment]
Hallo,

in meinem Beispiel wollte ich aufzeigen an welcher Stelle welche Variable (und in welchem Format) diese an die Klasse FastBill übergeben werden muss.
Damit dein Test funktioniert musst du die Zeile wie folgt ändern:

> $fastbill = new fastbill($FASTBILL_EMAIL, $FASTBILL_KEY);

Als dritten Parameter kannst du noch FASTBILL_PLUS übergeben, das ist aber auch der Default Wert.
Ich hoffe dir helfen zu können.

Gruß,
Andreas

–––

ZWEISCHNEIDER
Digitalschmiede

Wilhelmstraße 18
65185 Wiesbaden

T  0611 945 804 410
F  0611 945 804 419

www.zweischneider.de <http://www.zweischneider.de/>

**Comment by bert2002** [comment]
Hi Andreas,

alles klar, das erklärt es. Funktioniert auch wunderbar :) 
Bekomme zwar immer nur eine "1" aus dem error_log(print_r($temp)); aber mal schauen was das soll.

Danke.
