### ISSUE TITLE
Composer?

### ISSUE THREAD

**Issue by dennisoderwald** [Digitalschmiede/fastbill#7]
Wollt ihr nicht mal ein Composer Package zur Verfügung stellen? Das macht die Einbindung deutlich einfacher. :)

**Comment by Digitalschmiede** [comment]
Hallo,

Das Packet gibt es nun auch über den Composer ;)

**Comment by dennisoderwald** [comment]
\ô/ Thanks!

**Comment by dermoti** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mcXHI32d&#x2F;150-app-icons-fehlen"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> App Icons fehlen</a>
